// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';
import {updater} from '../models';

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function CreateBackup():Promise<string>;

export function CreateDocument(arg1:main.CreateDocumentInput):Promise<models.Document>;

export function DeleteDocument(arg1:number):Promise<void>;

export function DownloadAndApplyUpdate():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetDocument(arg1:number):Promise<models.Document>;

export function GetDocuments(arg1:string,arg2:string):Promise<Array<models.Document>>;

export function GetStats():Promise<models.IndexViewData>;

export function RestoreBackup():Promise<void>;

export function SelectDocumentFile():Promise<string>;

export function UpdateDocument(arg1:main.UpdateDocumentInput):Promise<void>;

