// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetDocuments(arg1, arg2) {
  return window['go']['main']['App']['GetDocuments'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function RestoreBackup() {
  return window['go']['main']['App']['RestoreBackup']();
}

export function SelectDocumentFile() {
  return window['go']['main']['App']['SelectDocumentFile']();
}

export function UpdateDocument(arg1) {
  return window['go']['main']['App']['UpdateDocument'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

